### ISSUE TITLE
make USE_PGXS=1

### ISSUE THREAD

**Issue by razersergey** [postgrespro/jsquery#49]
Hi
I try to installing jsquery and it fails with the error message
[make USE_PGXS=1](make: *** [/usr/lib/postgresql/16/lib/pgxs/src/makefiles/../../src/Makefile.global:792: jsquery_gram.c] Error 127)

**Comment by sokolcati** [comment]
Hi!
It looks like incorrect (or unidentified) environment variables.
If you want to place jsquery (or other module) outside the contrib folder and use USE _PGXS=1, you need the path to pg _config. Therefore, please run 
`export PATH=path_to_your_bin_folder:$PATH`
before starting compilation.
Or you also may use
`make USE_PGXS=1 PG_CONFIG=path_to_your_bin_folder/pg_config `
I hope everything works out. Otherwise I will wait for your error logs.
